/*
 * Copyright (C) 2012-present the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.pf4j;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;
import org.pf4j.test.PluginJar;
import org.pf4j.test.TestExtension;
import org.pf4j.test.TestPlugin;

import java.io.IOException;
import java.io.PrintWriter;
import java.net.URL;
import java.net.URLClassLoader;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Collections;
import java.util.Map;
import java.util.Set;

import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.Matchers.contains;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;

public class IndexedExtensionFinderTest {

    @TempDir
    Path pluginsPath;

    @TempDir
    Path applicationPath;

    /**
     * The application has its own {@code extensions.idx} and the plugin is loaded with
     * {@link ClassLoadingStrategy#APD}, so the application is consulted first. The extensions of the
     * plugin still have to be read from the plugin, see #449.
     */
    @Test
    public void shouldFindPluginExtensionsWhenApplicationComesFirst() throws Exception {
        PluginJar pluginJar = new PluginJar.Builder(pluginsPath.resolve("test-plugin.jar"), "test-plugin")
                .pluginClass(TestPlugin.class.getName())
                .pluginVersion("1.2.3")
                .extension(TestExtension.class.getName())
                .build();

        ClassLoader applicationClassLoader = createApplicationClassLoader();

        PluginManager pluginManager = new JarPluginManager(pluginsPath) {

            @Override
            protected PluginLoader createPluginLoader() {
                return new JarPluginLoader(this) {

                    @Override
                    protected PluginClassLoader createPluginClassLoader(Path pluginPath, PluginDescriptor pluginDescriptor) {
                        return new PluginClassLoader(pluginManager, pluginDescriptor, applicationClassLoader,
                            ClassLoadingStrategy.APD);
                    }

                };
            }

        };

        pluginManager.loadPlugins();

        assertEquals(1, pluginManager.getPlugins().size());

        IndexedExtensionFinder extensionFinder = new IndexedExtensionFinder(pluginManager);
        Map<String, Set<String>> pluginsStorages = extensionFinder.readPluginsStorages();

        Set<String> pluginStorage = pluginsStorages.get(pluginJar.pluginId());
        assertNotNull(pluginStorage);
        assertThat(pluginStorage, contains(TestExtension.class.getName()));
    }

    /**
     * A plugin without an extensions index of its own declares no extensions. The extensions of a
     * dependency belong to that dependency, which is read on its own turn.
     */
    @Test
    public void shouldNotReadTheExtensionsOfADependency() throws Exception {
        new PluginJar.Builder(pluginsPath.resolve("plugin-a.jar"), "plugin-a")
                .pluginVersion("1.0.0")
                .extension(TestExtension.class.getName())
                .build();

        new PluginJar.Builder(pluginsPath.resolve("plugin-b.jar"), "plugin-b")
                .pluginVersion("1.0.0")
                .manifestAttribute(ManifestPluginDescriptorFinder.PLUGIN_DEPENDENCIES, "plugin-a")
                .build();

        PluginManager pluginManager = new JarPluginManager(pluginsPath);
        pluginManager.loadPlugins();

        assertEquals(2, pluginManager.getPlugins().size());

        IndexedExtensionFinder extensionFinder = new IndexedExtensionFinder(pluginManager);
        Map<String, Set<String>> pluginsStorages = extensionFinder.readPluginsStorages();

        assertThat(pluginsStorages.get("plugin-a"), contains(TestExtension.class.getName()));
        assertEquals(Collections.emptySet(), pluginsStorages.get("plugin-b"));
    }

    /**
     * Creates a class loader for an application that declares an extension of its own.
     */
    private ClassLoader createApplicationClassLoader() throws IOException {
        Path metaInfPath = Files.createDirectories(applicationPath.resolve("META-INF"));
        try (PrintWriter writer = new PrintWriter(metaInfPath.resolve("extensions.idx").toFile())) {
            writer.println("# Generated by PF4J");
            writer.println("org.pf4j.test.ApplicationExtension");
        }

        URL[] urls = { applicationPath.toUri().toURL() };

        return new URLClassLoader(urls, getClass().getClassLoader());
    }

}
